language: scala

scala:
- 2.13.12
- 3.3.1

env:
  - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version

script:
- cd code
- sbt --info ++$TRAVIS_SCALA_VERSION publishLocal
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.9.0 test
- cd ../test-app
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.9.0 test
- cd ../test-app-filters
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.9.0 test
- cd ../code

after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt --info +publish; };'
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

sudo: false
