language: scala
jdk:
- oraclejdk8
scala:
- 2.12.7
script:
- cd code
- sbt --info ++$TRAVIS_SCALA_VERSION +publishLocal
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.7.0-RC3 +test
- cd ../test-app
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.7.0-RC3 +test
- cd ../test-app-filters
- sbt --info ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.7.0-RC3 +test
- cd ../code
after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt --info +publish; };'
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
sudo: false
